### ISSUE TITLE
feature extractor crash

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#23]
On commencing feature extraction:

`Starting feature extraction...
Traceback (most recent call last):
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\coding_tests\WaveletWidget.py", line 147, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\coding_tests\FeatureExtractorGUI.py", line 230, in extractFeatures
    self.feature_extractor.extract_features_from_animal(animal, re_write = self.re_write.isChecked(), n_cores = -1,
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\feature_extractor.py", line 130, in extract_features_from_animal
    with multiprocessing.Pool(processes=n_cores,initializer=my_worker_flist_init,
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x0000020A21CB5AF0>: attribute lookup <lambda> on __main__ failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

**Comment by mikailweston** [comment]
[dual_channel_features.json.txt](https://github.com/KullmannLab/pyecog2/files/6447987/dual_channel_features.json.txt)

**Comment by mfpleite** [comment]
Solved with last commit to Development_ML
