### ISSUE TITLE
sample rate bug when creating new project file

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#25]
On clicking  update project file button:

Error message:

Looking for files: F:\20210301_IntraHippoKA_DREADD\Left_virus\H5\1193429 \ *.h5
===== 2021.05.30 00:05:10 =====
Traceback (most recent call last):
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\coding_tests\ProjectGUI.py", line 209, in update_project_settings
    self.project.add_animal(Animal(id=id,eeg_folder=eeg_dir,video_folder=video_dir))
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\ProjectClass.py", line 91, in __init__
    self.update_eeg_folder(eeg_folder)
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\ProjectClass.py", line 129, in update_eeg_folder
    create_metafile_from_h5(file,duration)
  File "C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2\ProjectClass.py", line 27, in create_metafile_from_h5
    assert fs == int(fs_dict[tid])  # Check all tids have the same sampling rate

three files emailed to you: one that works, it's meta file and ne that creating a metafile fails

**Comment by mikailweston** [comment]
example file has hdf file where sample rate was not detected correctly, and H5 creation incorrectly set to 512SPS rather than 1024 for one channel.

We need the ability to manually set the FS when convertin NDF files to H5 files

**Comment by mfpleite** [comment]
Solved with last commit to Development_ML
