### ISSUE TITLE
NDF converter add animal list error

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#26]
remove animal, then try to add it again when it already exists (eg Animal 5)

```
===== 2021.06.11 18:06:10 =====
Traceback (most recent call last):
  File "C:\Users\Synapse\.conda\envs\pyecog2\lib\site-packages\pyqtgraph-0.11.0-py3.8.egg\pyqtgraph\parametertree\parameterTypes.py", line 426, in addChanged
    self.param.addNew(typ)
  File "C:\Users\Synapse\.conda\envs\pyecog2\lib\site-packages\pyecog2-0.0.1b0-py3.8.egg\pyecog2\coding_tests\convert_ndf_folder_gui.py", line 50, in addNew
  File "C:\Users\Synapse\.conda\envs\pyecog2\lib\site-packages\pyqtgraph-0.11.0-py3.8.egg\pyqtgraph\parametertree\Parameter.py", line 519, in addChild
    return self.insertChild(len(self.childs), child, autoIncrementName=autoIncrementName)
  File "C:\Users\Synapse\.conda\envs\pyecog2\lib\site-packages\pyqtgraph-0.11.0-py3.8.egg\pyqtgraph\parametertree\Parameter.py", line 562, in insertChild
    raise Exception("Already have child named %s" % str(name))
Exception: Already have child named Animal 5

```

**Comment by mfpleite** [comment]
Thanks. Now handling exception if name already exists and trying again with name "Animal n+1"
