### ISSUE TITLE
pyside updates prevent starting on Windows

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#31]
New pyecog2 environment and setup.py run. Error on attempting to start:

```
(pyecog2) C:\Users\mweston\Documents\GitHub\pyecog2\pyecog2>python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from PySide2 import QtCore, QtGui
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\site-packages\pyside2-5.15.2-py3.8-win-amd64.egg\PySide2\__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\site-packages\pyside2-5.15.2-py3.8-win-amd64.egg\PySide2\__init__.py", line 54, in _setupQtDirectories
    for dir in _additional_dll_directories(pyside_package_dir):
  File "C:\Users\mweston\Anaconda3\envs\pyecog2\lib\site-packages\pyside2-5.15.2-py3.8-win-amd64.egg\PySide2\__init__.py", line 26, in _additional_dll_directories    raise ImportError(shiboken2 + ' does not exist')
ImportError: C:\Users\mweston\Anaconda3\envs\pyecog2\lib\site-packages\shiboken2\libshiboken does not exist
```

**Comment by mikailweston** [comment]
work around: force reinstall PySide2 via pip

**Comment by mfpleite** [comment]
yeah there is some problem with pyside requiring numpy, but not solving it by itself. I have added numpy to the isntall_requires list, sort of solves it I think, but pyopengl is still complaining....
