### ISSUE TITLE
NDF converter error

### ISSUE THREAD

**Issue by HenryThinks** [KullmannLab/pyecog2#81]
Using the updated Python 3.11 development branch of Pyecog2, I'm picking up errors with the NDF converter. 

PyEcog

Could not close splash screen
Loading last opened Project: C:/Users/Henry/OneDrive - University College London/Analysis/pyecog/HMT_pilot_03.pyecog
C:\Users\Henry\miniconda3\envs\pyecog2_dev\Lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py:608: RuntimeWarning: overflow encountered in scalar add
  quantization_limit = (mn+mx) * 1.5e-15 # +/-10 discrete steps of double resolution
C:\Users\Henry\miniconda3\envs\pyecog2_dev\Lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py:608: RuntimeWarning: overflow encountered in scalar add
  quantization_limit = (mn+mx) * 1.5e-15 # +/-10 discrete steps of double resolution
C:\Users\Henry\miniconda3\envs\pyecog2_dev\Lib\site-packages\pyqtgraph\graphicsItems\ViewBox\ViewBox.py:608: RuntimeWarning: overflow encountered in scalar add
  quantization_limit = (mn+mx) * 1.5e-15 # +/-10 discrete steps of double resolution
Current version:0.0.1rc0
Latest version:v0.0.0.2
Ask to update PyEcog
Starting file conversion...
110 files between: 1717455600 and 1717887600
***
 Starting to convert VME1-06066 [21,22,23,24],512
***
Progress: |--------------------------------------------------| 0.0% Complete
Something unexpected went wrong loading [21, 22, 23, 24] from C:\Users\Henry\temp\ndf\M1717511643.ndf:
Traceback (most recent call last):
  File "c:\users\henry\pyecog2\pyecog2\ndf_converter.py", line 650, in convert_ndf
    ndf = NdfFile(filename, fs = fs, verbose = False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\henry\pyecog2\pyecog2\ndf_converter.py", line 115, in __init__
    self.get_valid_tids_and_fs()
  File "c:\users\henry\pyecog2\pyecog2\ndf_converter.py", line 156, in get_valid_tids_and_fs
    for tid, count in tid_message_counts.iteritems():
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henry\miniconda3\envs\pyecog2_dev\Lib\site-packages\pandas\core\generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'iteritems'
None

**Comment by mfpleite** [comment]
changed iteritems() to items(), should be resolved in Development_ML branch
